/*
 * Welcome
 */
package com.achess.server.UI;

/**
 *
 * @author achess
 */
public class MainForm extends javax.swing.JFrame {
    private static MainForm form;

    /**
     * Creates new form MainForm
     */
    private MainForm() {
        initComponents();
        customSettings();
    }
    
    private void customSettings(){
        this.setLocationRelativeTo(null);
        LineNumber line1 = new LineNumber(logText);
        this.jScrollPane1.setRowHeaderView(line1);
    }

    public static MainForm getForm(){
        if(form == null){
            form = new MainForm();            
        }
        return form;
    }
    
    public void log(String text){
        logText.append(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setBackground(new java.awt.Color(52, 55, 70));

        jScrollPane1.setForeground(java.awt.Color.white);

        logText.setEditable(false);
        logText.setBackground(new java.awt.Color(32, 32, 38));
        logText.setColumns(20);
        logText.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        logText.setRows(5);
        logText.setTabSize(1);
        logText.setCaretColor(new java.awt.Color(151, 123, 252));
        logText.setDisabledTextColor(java.awt.Color.white);
        logText.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                logTextComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(logText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logTextComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_logTextComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_logTextComponentAdded
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logText;
    // End of variables declaration//GEN-END:variables
}
