
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.achess.server.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVEQ = 56;
  public static final int PLUSPLUS = 38;
  public static final int STRING_LITERAL = 64;
  public static final int GTEQ = 48;
  public static final int MULT = 9;
  public static final int CHAR = 4;
  public static final int LTEQ = 47;
  public static final int MODEQ = 57;
  public static final int CASE = 30;
  public static final int DOUBLE = 6;
  public static final int LPAREN = 14;
  public static final int PRIVATE = 20;
  public static final int INT = 3;
  public static final int MINUS = 41;
  public static final int FOR = 34;
  public static final int STATIC = 21;
  public static final int RPAREN = 15;
  public static final int BOOLEAN_LITERAL = 62;
  public static final int OROR = 54;
  public static final int CHARACTER_LITERAL = 63;
  public static final int AND = 51;
  public static final int NOT = 42;
  public static final int SEMICOLON = 8;
  public static final int LT = 45;
  public static final int OR = 52;
  public static final int COMMA = 10;
  public static final int CLASS = 23;
  public static final int ANDAND = 53;
  public static final int DIV = 43;
  public static final int PLUSEQ = 58;
  public static final int MINUSEQ = 59;
  public static final int PLUS = 40;
  public static final int NULL_LITERAL = 66;
  public static final int IF = 27;
  public static final int THIS = 25;
  public static final int DOT = 7;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int MINUSMINUS = 39;
  public static final int RETURN = 36;
  public static final int NEW = 37;
  public static final int SUPER = 26;
  public static final int error = 1;
  public static final int EQEQ = 49;
  public static final int MULTEQ = 55;
  public static final int MOD = 44;
  public static final int BREAK = 35;
  public static final int VOID = 24;
  public static final int EQ = 13;
  public static final int SWITCH = 29;
  public static final int IMPORT = 17;
  public static final int COLON = 16;
  public static final int FLOATING_POINT_LITERAL = 61;
  public static final int LBRACE = 11;
  public static final int ELSE = 28;
  public static final int PROTECTED = 19;
  public static final int FINAL = 22;
  public static final int WHILE = 33;
  public static final int DEFAULT = 31;
  public static final int PUBLIC = 18;
  public static final int RBRACE = 12;
  public static final int STRING = 5;
  public static final int GT = 46;
  public static final int DO = 32;
  public static final int NOTEQ = 50;
  public static final int IDENTIFIER = 65;
  public static final int INTEGER_LITERAL = 60;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "INT",
  "CHAR",
  "STRING",
  "DOUBLE",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "IMPORT",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "STATIC",
  "FINAL",
  "CLASS",
  "VOID",
  "THIS",
  "SUPER",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "DO",
  "WHILE",
  "FOR",
  "BREAK",
  "RETURN",
  "NEW",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "NOT",
  "DIV",
  "MOD",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "EQEQ",
  "NOTEQ",
  "AND",
  "OR",
  "ANDAND",
  "OROR",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "PLUSEQ",
  "MINUSEQ",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL"
  };
}

