
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.achess.client.jsonParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLASSES_LITERAL = 8;
  public static final int RBRACE = 3;
  public static final int FUNCTION_LITERAL = 14;
  public static final int LBRACKET = 4;
  public static final int VARIABLES_LITERAL = 10;
  public static final int COLON = 7;
  public static final int LBRACE = 2;
  public static final int SCORE_LITERAL = 12;
  public static final int RBRACKET = 5;
  public static final int STRING_LITERAL = 19;
  public static final int TYPE_LITERAL = 15;
  public static final int COMMA = 6;
  public static final int EOF = 0;
  public static final int METHODS_LITERAL = 9;
  public static final int COMMENTS_LITERAL = 11;
  public static final int error = 1;
  public static final int INTEGER_LITERAL = 18;
  public static final int TEXT_LITERAL = 17;
  public static final int PARAMETERS_LITERAL = 16;
  public static final int NAME_LITERAL = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "COLON",
  "CLASSES_LITERAL",
  "METHODS_LITERAL",
  "VARIABLES_LITERAL",
  "COMMENTS_LITERAL",
  "SCORE_LITERAL",
  "NAME_LITERAL",
  "FUNCTION_LITERAL",
  "TYPE_LITERAL",
  "PARAMETERS_LITERAL",
  "TEXT_LITERAL",
  "INTEGER_LITERAL",
  "STRING_LITERAL"
  };
}

