/*
 * Welcome
 */

package com.achess.client.ui;

/**
 *
 * @author achess
 */
public class HtmlPanel extends javax.swing.JPanel {
    private static HtmlPanel panel;
    /** Creates new form HtmlPanel */
    private HtmlPanel() {
        initComponents();
    }
    
    public static HtmlPanel getHtml(){
        if(panel == null){
            panel = new HtmlPanel();
        }
        return panel;
    }
    
    public void setHtmlFormat(String text){
        this.htmlLabel.setText(text);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        htmlLabel = new javax.swing.JLabel();

        htmlLabel.setText("HTML");
        jScrollPane1.setViewportView(htmlLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel htmlLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
