
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.achess.client.copyParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 24;
  public static final int LBRACKET = 40;
  public static final int PARAMETROS = 36;
  public static final int MULT = 49;
  public static final int TIPO = 33;
  public static final int NOMBRE = 35;
  public static final int TD_OPEN = 9;
  public static final int FOR_CLOSE = 13;
  public static final int FUNCION = 34;
  public static final int SCORE = 28;
  public static final int INTEGER = 22;
  public static final int LPAREN = 38;
  public static final int TH_OPEN = 8;
  public static final int COMENTARIOS = 32;
  public static final int DPESOS = 51;
  public static final int ITERADOR = 19;
  public static final int MINUS = 48;
  public static final int HASTA = 20;
  public static final int RPAREN = 39;
  public static final int H1_OPEN = 3;
  public static final int SEMICOLON = 42;
  public static final int BR_OPEN = 18;
  public static final int TR_OPEN = 7;
  public static final int TABLE_CLOSE = 14;
  public static final int COMMA = 44;
  public static final int DIV = 50;
  public static final int PLUS = 47;
  public static final int CLASES = 29;
  public static final int DOT = 45;
  public static final int HTML_OPEN = 2;
  public static final int EOF = 0;
  public static final int RBRACKET = 41;
  public static final int error = 1;
  public static final int TEXTO_COMENTARIO = 37;
  public static final int EQ = 46;
  public static final int H1_CLOSE = 11;
  public static final int TD_CLOSE = 17;
  public static final int COLON = 43;
  public static final int H2_CLOSE = 12;
  public static final int TH_CLOSE = 16;
  public static final int METODOS = 30;
  public static final int TR_CLOSE = 15;
  public static final int VARIABLES = 31;
  public static final int H2_OPEN = 4;
  public static final int FOR_OPEN = 5;
  public static final int STRING = 21;
  public static final int HTML_CLOSE = 10;
  public static final int TEXT = 26;
  public static final int TABLE_OPEN = 6;
  public static final int GT = 52;
  public static final int RESULT = 27;
  public static final int INTEGER_LITERAL = 23;
  public static final int IDENTIFIER = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HTML_OPEN",
  "H1_OPEN",
  "H2_OPEN",
  "FOR_OPEN",
  "TABLE_OPEN",
  "TR_OPEN",
  "TH_OPEN",
  "TD_OPEN",
  "HTML_CLOSE",
  "H1_CLOSE",
  "H2_CLOSE",
  "FOR_CLOSE",
  "TABLE_CLOSE",
  "TR_CLOSE",
  "TH_CLOSE",
  "TD_CLOSE",
  "BR_OPEN",
  "ITERADOR",
  "HASTA",
  "STRING",
  "INTEGER",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "TEXT",
  "RESULT",
  "SCORE",
  "CLASES",
  "METODOS",
  "VARIABLES",
  "COMENTARIOS",
  "TIPO",
  "FUNCION",
  "NOMBRE",
  "PARAMETROS",
  "TEXTO_COMENTARIO",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "DOT",
  "EQ",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "DPESOS",
  "GT"
  };
}

